remote_state:
  network:
    resource_group_name: rg-tfstate-platform
    storage_account_name: sttfstateplatform
    container_name: tfstate
    key: platform/network/testing.tfstate

route_tables:
  - name: rt-app-egress
    subnet_keys:
      - app
      - data
    routes:
      - name: default-to-firewall
        address_prefix: 0.0.0.0/0
        next_hop_type: VirtualAppliance
        next_hop_in_ip_address: 10.10.100.4

governance:
  single_source_of_truth: git
  change_model: pull-request
  required_reviews: 1
  error_budget_policy: review-before-routing-change
