apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-data
  namespace: demo
  labels:
    app.kubernetes.io/part-of: azure-platform-lab
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
