apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-workload
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - web.testing.example.internal
      secretName: web-testing-tls
  rules:
    - host: web.testing.example.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-workload
                port:
                  number: 80
