apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workload-testing
resources:
  - ../../../blueprint-templates/platform-baseline
  - ../../../blueprint-templates/web-workload
  - ingress.yaml
labels:
  - pairs:
      environment: testing
      platform-environment: nonproduction
    includeSelectors: true
replicas:
  - name: web-workload
    count: 1
patches:
  - target:
      version: v1
      kind: Namespace
      name: platform-workload
    path: namespace-patch.yaml
